AlchemyPages/Models/Player.cs
using System.ComponentModel.DataAnnotations;

namespace AlchemyPages.Models
{
    public class Player
    {
        public int PlayerID { get; set; }

        [Required] public string FirstName { get; set; }
        [Required] public string LastName { get; set; }

        public ICollection<IngredientEncounter> IngredientEncounters { get; set; }
    }
}

AlchemyPages/Pages/Players/AddPlayerKnowledge.cshtml.cs
using AlchemyPages.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlchemyPages.Models;

namespace AlchemyPages.Pages.Players
{
    public class AddPlayerKnowledgeModel : PageModel
    {
        private readonly ApplicationDBContext context;

        public AddPlayerKnowledgeModel(ApplicationDBContext context)
        {
            this.context = context;  
        }

        [BindProperty] public PlayerKnowledge PlayerKnowledge { get; set; }

        public SelectList Players { get; set; }
        public SelectList Ingredients { get; set; }
        public SelectList QualitiesKnown { get; set; }

        public async Task OnGetAsync()
        {
            Players = new SelectList(await context.Players.ToListAsync(), "PlayerID", "FirstName");
            Ingredients = new SelectList(await context.Ingredients.ToListAsync(), "Id", "Name");
            QualitiesKnown = new SelectList(new[] { 1, 2, 3 });

            if (Players == null || Ingredients == null || QualitiesKnown == null)
            {
                
                Console.WriteLine("either players Ingredients or Quality options are null");

            }
            
        }

        public async Task<IActionResult> OnPostAsync()
        {

            bool alreadyExists = await context.PlayerKnowledges.AnyAsync(pk => pk.PlayerID == PlayerKnowledge.PlayerID && pk.IngredientId == PlayerKnowledge.IngredientId);

            if (!ModelState.IsValid)
            {

                Console.WriteLine("Model state not valid");
                await OnGetAsync(); return Page();

            }
            if (alreadyExists)
            {
                ModelState.AddModelError(string.Empty, "this ingredient is known already");
                await OnGetAsync();
                return Page();
            }


            context.PlayerKnowledges.Add(PlayerKnowledge);
            Console.WriteLine("content added to db");
            await context.SaveChangesAsync();
            Console.WriteLine("content saved");
            return RedirectToPage("/Admin/index");
        }

    }
}

AlchemyPages/Pages/Players/CreatePlayer.cshtml.cs
using AlchemyPages.Models;
using AlchemyPages.Pages.Players;
using AlchemyPages.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AlchemyPages.Migrations;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;

namespace AlchemyPages.Pages.Players
{
    public class CreatePlayerModel : PageModel
    {
        private readonly ApplicationDBContext context;

        [BindProperty] public PlayerCreate playerCreate { get; set; } 


        public CreatePlayerModel(ApplicationDBContext context)
        {
            this.context = context;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Debug.WriteLine("not a valid model");
                return Page();
            }

            var Player = new Player
            {
                FirstName = playerCreate.FirstName,
                LastName = playerCreate.LastName,

            };

            Debug.WriteLine($"player name is:{Player.FirstName}");

            context.Players.Add(Player);
            await context.SaveChangesAsync();
            return RedirectToPage("/Players/Index");


        }


    }
}

AlchemyPages/Pages/Players/DeletePlayer.cshtml.cs
using AlchemyPages.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AlchemyPages.Models;

namespace AlchemyPages.Pages.Players
{
    public class DeletePlayerModel : PageModel
    {
        private readonly ApplicationDBContext context;

        [BindProperty] public Player Player { get; set; }

        public DeletePlayerModel(ApplicationDBContext context)
        {
            this.context = context;
        }


        public async Task<IActionResult> OnGetAsync(int PlayerID)
        {
            Player = await context.Players.FindAsync(PlayerID);

            if (Player == null)
            {
                return RedirectToPage("/Player/Index");
            }
            return Page();

        }

        public async Task<IActionResult> OnPostAsync()
        {
            var playerToDelete = await context.Players.FindAsync(Player.PlayerID);

            if (playerToDelete != null)
            {
                context.Players.Remove(playerToDelete);
                context.SaveChanges();
            }

            return RedirectToPage("/Players/Index");
        }
    }


}

AlchemyPages/Pages/Players/DeletePlayerKnowledge.cshtml.cs
using AlchemyPages.Models;
using AlchemyPages.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Threading.Tasks.Dataflow;

namespace AlchemyPages.Pages.Players
{
    public class DeletePlayerKnowledgeModel : PageModel
    {
        private readonly ApplicationDBContext context;

       [BindProperty] public PlayerKnowledge PlayerKnowledge { get; set; }

        public DeletePlayerKnowledgeModel(ApplicationDBContext context)
        {
            this.context = context;
        }


      

        public async Task<IActionResult> OnGetAsync(int Id)
        {
           
            PlayerKnowledge = await context.PlayerKnowledges.Include(playerK => playerK.Ingredient).FirstOrDefaultAsync(playerK => playerK.PlayerKnowledgeID == Id);
           
            if (PlayerKnowledge == null)
            {
                Debug.WriteLine("player knowledge NULL");
                return RedirectToPage("/Players/EditPlayerKnowledge");
            }

            return Page();

        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            Debug.WriteLine("on POST Async hit");


            //if (PlayerKnowledge == null || PlayerKnowledge.PlayerKnowledgeID == 0)
            //{
            //    return RedirectToPage("/Players/EditPlayerKnowledge");
            //}

            var PlayerknowledgeToDelete =  await context.PlayerKnowledges.FindAsync(id);

            if (PlayerknowledgeToDelete != null)
            {
                context.PlayerKnowledges.Remove(PlayerknowledgeToDelete);
                context.SaveChanges();
            }

            return RedirectToPage("/Players/EditPlayerKnowledge");


        }
    }
}

AlchemyPages/Pages/Players/EditPlayer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AlchemyPages.Services;
using AlchemyPages.Models;
using System.Xml.Linq;
using System.Diagnostics;

namespace AlchemyPages.Pages.Players
{
    public class EditPlayerModel : PageModel
    {
        [BindProperty] public PlayerCreate playerCreate { get; set; } = new PlayerCreate();
        public Player Player { get; set; } = new();

        private readonly ApplicationDBContext context;

     

        public EditPlayerModel(ApplicationDBContext context)
        {
            this.context = context; 

        }



        public async Task<IActionResult> OnGetAsync(int PlayerID)
        {
            var displayPlayerToBeEdited = await context.Players.FindAsync(PlayerID);

            if (displayPlayerToBeEdited == null)
            {
                return RedirectToPage("/Players/Index");
            }

            Player = displayPlayerToBeEdited;

            playerCreate.FirstName = displayPlayerToBeEdited.FirstName;
            playerCreate.LastName = displayPlayerToBeEdited.LastName;


            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int PlayerID)
        {
            var playerToBeEdited = context.Players.Find(PlayerID);

            if (playerToBeEdited == null)
            {
                Debug.WriteLine("not a valid model");
                return Page();
            }

            playerToBeEdited.FirstName = playerCreate.FirstName;
            playerToBeEdited.LastName = playerCreate.LastName;

            await context.SaveChangesAsync();
            return RedirectToPage("/Players/Index");
        }

    }
}

AlchemyPages/Pages/Players/EditPlayerKnowledge.cshtml.cs
using AlchemyPages.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AlchemyPages.Services;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace AlchemyPages.Pages.Players
{
    public class EditPlayerKnowledgeModel : PageModel
    {
        private readonly ApplicationDBContext context;
        [BindProperty(SupportsGet= true)] public int? SelectedPlayerID { get; set; }
        public SelectList Players { get; set; }
        public List<PlayerKnowledge> PlayerKnowledgeList { get; set; }


        public EditPlayerKnowledgeModel(ApplicationDBContext context)
        {
            this.context = context;

        }


        public async Task<IActionResult> OnGetAsync()
        {
            Players = new SelectList(await context.Players.ToListAsync(), "PlayerID", "FirstName");

            if (SelectedPlayerID != null)
            {
                PlayerKnowledgeList = await context.PlayerKnowledges.Where(pk => pk.PlayerID == SelectedPlayerID).Include(pk => pk.Ingredient).OrderByDescending(pk => pk.IngredientId).ToListAsync();
            }
            else
            {
                PlayerKnowledgeList = new List<PlayerKnowledge>();
            }

            return Page();

        }

        public async Task<IActionResult> OnPostUpdateAsync(int PlayerKnowledgeID, int QualitiesKnown)
        {
            var entry = await context.PlayerKnowledges.FindAsync(PlayerKnowledgeID);
            if(entry != null)
            {
                entry.QualitiesKnown = QualitiesKnown;
                await context.SaveChangesAsync();
            }

            return RedirectToPage(new { SelectedPlayerID });
        }


    }
}

AlchemyPages/Pages/Players/Index.cshtml.cs
using AlchemyPages.Models;
using AlchemyPages.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlchemyPages.Pages.Players
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDBContext context;
        public List<Player> playerList = new();

        public IndexModel (ApplicationDBContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            playerList = await context.Players.OrderByDescending(i => i.PlayerID).ToListAsync();

            if (playerList == null)
            {
                return RedirectToPage("/Shared/Index");
            }

            return Page();
        }
    }
}

AlchemyPages/Pages/Players/PlayerView.cshtml.cs
using AlchemyPages.Models;
using AlchemyPages.Services;
using Azure.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AlchemyPages.Pages.Players
{
    public class PlayerViewModel : PageModel
    {
        private readonly ApplicationDBContext context;
        public List<Player> playerList = new();

        public Player Player { get; set; } = new();
        public PlayerKnowledge Knowledge { get; set; }
        public Ingredient Ingredient { get; set; }

        public List<PlayerKnowledge> KnowledgeList { get; set; }

        private readonly IWebHostEnvironment _environment;

        public PlayerViewModel(ApplicationDBContext context,IWebHostEnvironment environment)
        {
            this.context = context;
            _environment = environment;

        }

        public async Task<IActionResult> OnGetAsync(int PlayerID)
        {

            var playerToDisplay = await context.Players.FindAsync(PlayerID);
           

            if (playerToDisplay == null)
            {
                return RedirectToPage("/Players/Index");
            }

            Player = playerToDisplay;

            KnowledgeList = await context.PlayerKnowledges.Where(record => record.PlayerID == PlayerID).Include(record => record.Ingredient).ToListAsync();

            foreach (var record in KnowledgeList)
            {
                if (!string.IsNullOrEmpty(record.Ingredient.qualityOne))
                {
                    record.Ingredient.qualityOneIconPath = Path.Combine("property-icons", record.Ingredient.qualityOne + ".png");
                }
                if (!string.IsNullOrEmpty(record.Ingredient.qualityTwo))
                {
                    record.Ingredient.qualityTwoIconPath = Path.Combine("property-icons", record.Ingredient.qualityTwo + ".png");
                }
                if (!string.IsNullOrEmpty(record.Ingredient.qualityThree))
                {
                    record.Ingredient.qualityThreeIconPath = Path.Combine("property-icons", record.Ingredient.qualityThree + ".png");
                }
            }

            return Page();


        }
    }
}

AlchemyPages/Pages/Players/AddPlayerKnowledge.cshtml
@page
@model AlchemyPages.Pages.Players.AddPlayerKnowledgeModel
@{
}



<form method="post">

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

  <div class="row mb-3">
        <div class="col-md-3 me-3">
            <label class="form-label w-100 text-start"> <strong>Player</strong> </label>
            <select class="form-select w-100" asp-for="PlayerKnowledge.PlayerID" asp-items="Model.Players"></select>
      </div>
        <div class="col-md-3 me-3">
            <label class ="form-label w-100 text-start"> <strong>Ingredient</strong> </label>
            <select class="form-select w-100" asp-for="PlayerKnowledge.IngredientId" asp-items="Model.Ingredients"></select>
      </div>
        <div class="col-md-3 me-3">
            <label class="form-label w-100 text-start"> <strong>Qualities Known</strong> </label>
            <select class="form-select w-100" asp-for="PlayerKnowledge.QualitiesKnown" asp-items="Model.QualitiesKnown"></select>
      </div>
        <div class="col-md-2 align-self-end">
      <button type="submit" class="btn btn-primary w-100">Submit</button>
      </div>
  </div>

    
</form>

<div class="col">
    <a class="btn btn-primary w-100" asp-page="/Admin/Index">Return To Admin</a>
</div>

AlchemyPages/Pages/Players/CreatePlayer.cshtml
@page
@model AlchemyPages.Pages.Players.CreatePlayerModel
@{
}

<h2 class="text-center mb-4">New Player</h2>

<form method="post" enctype="multipart/form-data">
    <div class="row g-2 mb-3">

        <div class="col-lg-6">
            
            <div class="h-100">
                <div class="card-header">
                    Player Details
                </div>

            <div class="card-body">

                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label"> First Name </label>
                    <div class="col-sm-8">
                        <input class="form-control" asp-for="playerCreate.FirstName">
                        <span asp-validation-for="playerCreate.FirstName" class=" text-danger"> </span>
                    </div>
                </div>
                    
                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label"> Last Name </label>
                    <div class="col-sm-8">
                        <input class="form-control" asp-for="playerCreate.LastName">
                        <span asp-validation-for="playerCreate.LastName" class=" text-danger"> </span>
                    </div>
                </div>
                     
            </div>
            



            </div>


        </div>

    </div>

    <button type="submit" class="btn btn-primary me-2">Submit</button>
    <a class="btn btn-outline-primary" asp-page="/Players/Index" role="button">cancel</a>

</form>

AlchemyPages/Pages/Players/DeletePlayer.cshtml
@page
@model AlchemyPages.Pages.Players.DeletePlayerModel
@{
}

<h2 class="text-center mb-3 " style="color: red">Are you sure you want to delete this player? </h2>

<div>
    <p class="text-centre mb-3" style="color: dimgrey">@Model.Player.FirstName @Model.Player.LastName</p>

    <form method="post">

        <input type="hidden" asp-for="Player.PlayerID" />
        <button type="submit" class="btn btn-danger"> Yes, Delete</button>
        <a class="btn btn-secondary" asp-page="/Players/Index" role="button">Cancel</a>
    </form>

</div>

AlchemyPages/Pages/Players/DeletePlayerKnowledge.cshtml
@page
@model AlchemyPages.Pages.Players.DeletePlayerKnowledgeModel
@{
}
<h2 class="text-center mb-3 " style="color:red">Are you sure you want to delete this entry?</h2>

<div>
    <p class="text-centre mb-3" style="color: dimgrey ">@Model.PlayerKnowledge.Ingredient.Name</p>

    <form method="post">
    <input type="hidden" name="id" value="@Model.PlayerKnowledge.PlayerKnowledgeID" />
    <button type="submit" class="btn btn-danger"> Yes, Delete</button>
    <a class="btn btn-secondary" asp-page="/Players/EditPlayerKnowledge" role="button">Cancel</a>
    </form>

</div>

AlchemyPages/Pages/Players/EditPlayer.cshtml
@page
@model AlchemyPages.Pages.Players.EditPlayerModel
@{
}

<h2 class="text-center mb-3">Edit Player</h2>

<form method="post">

    <div class="row g-2 mb-3">

        <div class="col-lg-6">

            <div class="card h-100">


                <div class="card-header">
                    Player Details
                </div>

                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label">Ingredient Id</label>
                    <div class="col-sm-8">
                        <input class="form-control-plaintext" readonly value="@Model.Player.PlayerID">

                    </div>

                </div>

                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label">Player First Name</label>
                    <div class="col-sm-8">
                        <input class="form-control" asp-for="playerCreate.FirstName">
                        <span asp-validation-for="playerCreate.FirstName" class="text-danger"> </span>
                    </div>

                </div>

                <div class="row mb-3">
                    <label class="col-sm-4 col-form-label">Player Last Name</label>
                    <div class="col-sm-8">
                        <input class="form-control" asp-for="playerCreate.LastName">
                        <span asp-validation-for="playerCreate.LastName" class="text-danger"> </span>
                    </div>

                </div>



                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-outline-primary" asp-page="/Players/Index" role="button">cancel</a>


            </div>

        </div>

    </div>

</form>

AlchemyPages/Pages/Players/EditPlayerKnowledge.cshtml
@page
@model AlchemyPages.Pages.Players.EditPlayerKnowledgeModel
@{
}
<h2 class="text-centre mb-3"> Edit Playerbook </h2>


<form method="get">

    <div class="mb-3">
        <label class="form-label"><strong>Select Player</strong></label>
        <select asp-for="SelectedPlayerID" asp-items="Model.Players" class="form-control" onchange="this.form.submit()">
            <option value="">-- Select Player --</option>
        </select>
    </div>

</form>

@if (Model.PlayerKnowledgeList != null && Model.PlayerKnowledgeList.Any())
{
    <table class="table">
        <thead>
            <tr><th>Ingredient Name</th> <th>Qualities Discovered</th></tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PlayerKnowledgeList)
            {
                <tr>
                    <td>@item.Ingredient.Name</td>  
                    <td>

                        <form method="post" asp-page-handler="Update" class="d-flex align-items-center gap-2 mb-0">
                            <input type="hidden" name="PlayerKnowledgeID" value="@item.PlayerKnowledgeID" />
                            <input type="text"
                                   name="QualitiesKnown"
                                   value="@item.QualitiesKnown"
                                   class="form-control form-control-sm w-auto align-middle"
                                   style="height: calc(1.5em + .5rem + 2px); padding: .25rem .5rem;" />
                            <button type="submit" class="btn btn-primary btn-sm align-middle">Update</button>
                            
                            <a class="btn btn-warning btn-sm align-middle" asp-page="/Players/DeletePlayerKnowledge" asp-route-id="@item.PlayerKnowledgeID">Delete</a>

                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else if (Model.SelectedPlayerID != null)
{
    <p>No Knowledge entries found for this player</p>
}

<div class="col">
    <a class="btn btn-primary w-100" asp-page="/Admin/Index">Return To Admin</a>
</div>

AlchemyPages/Pages/Players/Index.cshtml
@page
@model AlchemyPages.Pages.Players.IndexModel
@{
}
<h2 class="text-center mb-2">Players</h2>
<a class="btn btn-primary" asp-page="/Players/CreatePlayer">New Player</a>

<div style="overflow-x:auto;">
    <table class="table">
        <thead>
            <tr>
                <th>Player Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th style="width:120px;">Actions</th>

            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var player in Model.playerList) @* check to see if this is correct, may need to be direct - 7/5/25 it is correct  *@
            {
                <tr>
                    <td>@player.PlayerID</td>
                    <td>@player.FirstName</td>
                    <td>@player.LastName</td>

                    <td style="white-space:nowrap">
                    <a class=" btn btn-primary btn-sm" asp-page="/Players/EditPlayer" asp-route-PlayerID="@player.PlayerID"> Edit </a>   
                    <a class=" btn btn-danger btn-sm" asp-page="/Players/DeletePlayer" asp-route-PlayerID="@player.PlayerID"> Delete </a> 
                    <a class="btn btn-sm" style="background-color: green; color: white;" asp-page="/Players/PlayerView" asp-route-PlayerID="@player.PlayerID">View craftbook</a> @* Chage asp page to variable for that specific player *@

                    </td>


                </tr>
            }
            

        </tbody>
    </table>

</div>

AlchemyPages/Pages/Players/PlayerView.cshtml
@page
@model AlchemyPages.Pages.Players.PlayerViewModel
@{
}

<h2 class="text-center mb-3">@Model.Player.FirstName Alchemy Book</h2>



@* load data from player sql table and display data from asscoiated encounter table *@
@* Also make sure that the player ID is passed through here. *@

@* 
<h2 class=" text-center mb-3">Player CraftBook</h2> *@

<div class="row mb-3">

    <label class="col-sm-4 col-form-label">@Model.Player.FirstName</label>
    
    <div style="overflow-x:auto;">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Element</th>
                    <th>Description</th>
                    <th>Quality I</th>
                    <th>Quality II</th>
                    <th>Quality III</th>
                    <th>Image</th>
                    <th>Test</th> @*Delete this later*@
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach (var record in Model.KnowledgeList)
                {
                    <tr>
                        <td>@record.Ingredient.Name</td>
                        <td>@record.Ingredient.Type</td>
                        <td>@record.Ingredient.Element</td>
                        <td>@record.Ingredient.Description</td>
                        <td>
                            @if (record.QualitiesKnown >= 1 && !string.IsNullOrEmpty(record.Ingredient.qualityOne))
                            {
                                <img src="~/@record.Ingredient.qualityOneIconPath" alt="@record.Ingredient.qualityOne" />
                            }
                            else
                            {
                                <span class="text-muted"> Unknown </span>
                            }
                        </td>
                        <td>
                            @if (record.QualitiesKnown >= 2 && !string.IsNullOrEmpty(record.Ingredient.qualityTwo))
                            {
                                <img src="~/@record.Ingredient.qualityTwoIconPath" alt="@record.Ingredient.qualityTwo" />
                            }
                            else
                            {
                                <span class="text-muted"> Unknown </span>
                            }
                        </td>
                        <td>
                            @if (record.QualitiesKnown >= 3 && !string.IsNullOrEmpty(record.Ingredient.qualityThree))
                            {
                                <img src="~/@record.Ingredient.qualityThreeIconPath" alt="@record.Ingredient.qualityThree" />
                            }
                            else
                            {
                                <span class="text-muted"> Unknown </span>
                            }
                        </td>

                        <td>
                            @if (!string.IsNullOrEmpty(record.Ingredient.imageFileLocation))
                            {
                                <img src="@record.Ingredient.imageFileLocation" style="max-width: 100px; height:auto;" alt="Ingredient Image" />
                            }
                            else
                            {
                                <span> No Image </span>
                            }

                        </td>


                       
                    </tr>
                }
            </tbody>

        </table>


</div>